version: "3.8"
services:
  app:
    container_name: nestjs-template-server
    build:
      context: ./
      dockerfile: ./docker/nest/dev.dockerfile
    working_dir: /home/node/app
    command: npm start
    restart: unless-stopped
    tty: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - template-nest-network
    depends_on:
      - database
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      APP_ENV: dev
      APP_PORT: 5000
      DB_DEBUG: 1
      DB_HOST: database
      DB_DATABASE: template
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      CACHE_DATABASE: ${CACHE_DATABASE}
      CACHE_TTL: ${CACHE_TTL}

  database:
    container_name: postgres-template-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - template-database:/var/lib/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - template-nest-network

  redis:
    container_name: redis-template
    image: redis
    restart: unless-stopped
    ports:
      - 6383:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - template-nest-network
    volumes:
      - neko-template-cache:/data

networks:
  template-nest-network:
    driver: bridge

volumes:
  template-database:
    driver: local
  neko-template-cache:
    driver: local
